version: '4'

services:
  main.api:
    image: mainapi
    build:
      context: .
      dockerfile: Main.API/Dockerfile

  Validator1-redis:
    image: redis:latest
    command: redis-server
    container_name: Validator1-redis
    volumes:
      - Validator1-redis:/var/lib/redis
      - Validator1-redis-config:/usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    ports:
      - 6370:6379

  Validator2-redis:
    image: redis:latest
    command: redis-server
    container_name: Validator2-redis
    volumes:
      - Validator2-redis:/var/lib/redis
      - Validator2-redis-config:/usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    ports:
      - 6371:6379

  Validator3-redis:
    image: redis:latest
    command: redis-server
    container_name: Validator3-redis
    volumes:
      - Validator3-redis:/var/lib/redis
      - Validator3-redis-config:/usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    ports:
      - 6379:6379
      
  Validator1-Database:
        container_name: Validator1-Database
        ports:
          - "8092:1433"
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
          SA_PASSWORD: "LitwoOjczyznoMoja1234@"
          ACCEPT_EULA: "Y"
        networks:
          - redis-network

  Validator2-Database:
        container_name: Validator2-Database
        ports:
          - "8093:1433"
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
          SA_PASSWORD: "LitwoOjczyznoMoja1234@"
          ACCEPT_EULA: "Y"
        networks:
          - redis-network
  
  Validator3-Database:
        container_name: Validator3-Database
        ports:
          - "8094:1433"
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
          SA_PASSWORD: "LitwoOjczyznoMoja1234@"
          ACCEPT_EULA: "Y"
        networks:
          - redis-network

  validatorA:
        container_name: ValidatorA
        image: electronicvotingvalidator
        build:
          context: .
          dockerfile: Validator.API/Dockerfile
        environment:
          - CONTAINER_NAME=ValidatorA
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - REDIS_URL=Validator1-redis:6379
          - ConnectionStrings_Database=Server=Validator1-Database;User Id=sa;Password=LitwoOjczyznoMoja1234@;TrustServerCertificate=true
        depends_on:
          - Validator1-Database
        networks:
          - redis-network
        ports:
          - "9000:80"
          - "9001:443"
          - "5001:5000"
  validatorB:
        container_name: ValidatorB
        image: electronicvotingvalidator
        build:
          context: .
          dockerfile: Validator.API/Dockerfile
        environment:
          - CONTAINER_NAME=ValidatorB
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - REDIS_URL=Validator2-redis:6379
          - ConnectionStrings_Database=Server=Validator2-Database;User Id=sa;Password=LitwoOjczyznoMoja1234@;TrustServerCertificate=true
        depends_on:
          - Validator2-redis
          - Validator2-Database
        networks:
          - redis-network
        ports:
          - "9002:80"
          - "9003:443"
          - "5002:5000"
  validatorC:
    container_name: ValidatorC
    image: electronicvotingvalidator
    build:
        context: .
        dockerfile: Validator.API/Dockerfile
    environment:
        - CONTAINER_NAME=ValidatorC
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - REDIS_URL=Validator3-redis:6379
        - ConnectionStrings_Database=Server=Validator3-Database;User Id=sa;Password=LitwoOjczyznoMoja1234@;TrustServerCertificate=true
    depends_on:
        - Validator3-redis
        - Validator3-Database
    networks:
      - redis-network
    ports:
        - "9004:80"
        - "9005:443"
        - "5003:5000"

networks:
  redis-network:
    driver: bridge

volumes:
  Validator1-redis:
  Validator1-redis-config:
  Validator2-redis:
  Validator2-redis-config:
  Validator3-redis:
  Validator3-redis-config:
