version: '3.5'

services:
  MainDb:
    container_name: MainDatabase
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "8090:1433"
    environment:
      SA_PASSWORD: "LitwoOjczyznoMoja1234@"
      ACCEPT_EULA: "Y"
  electronicvoting.api:
    container_name: ValidatorA
    image: electronicvotingapi
    build:
      context: .
      dockerfile: ElectronicVoting.API/Dockerfile
    environment:
      - CONTAINER_NAME=ValidatorA
    depends_on:
      - MainDb
      - DatabaseA
    ports:
      - "9000:80"
      - "9001:443"
      - "5001:5000"
  DatabaseA:
    container_name: DatabaseA
    ports:
      - "8091:1433"
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "LitwoOjczyznoMoja1234@"
      ACCEPT_EULA: "Y"

  ValidatorB:
    container_name: ValidatorB
    image:  electronicvotingapi
    build:
      context: .
      dockerfile: ElectronicVoting.API/Dockerfile
    environment:
        - CONTAINER_NAME=ValidatorB
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "9002:80"
      - "9003:443"
      - "5002:5000"
    depends_on:
      - MainDb
      - DatabaseB
  DatabaseB:
    container_name: DatabaseB
    ports:
      - "8092:1433"
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "LitwoOjczyznoMoja1234@"
      ACCEPT_EULA: "Y"